/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class aleksandarlazic_ra1042014_example_com_taskmanager_NativeClass */

#ifndef _Included_aleksandarlazic_ra1042014_example_com_taskmanager_NativeClass
#define _Included_aleksandarlazic_ra1042014_example_com_taskmanager_NativeClass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     aleksandarlazic_ra1042014_example_com_taskmanager_NativeClass
 * Method:    racunajProcente
 * Signature: (FF)F
 */
JNIEXPORT jfloat JNICALL Java_aleksandarlazic_ra1042014_example_com_taskmanager_NativeClass_racunajProcente
  (JNIEnv *, jobject, jfloat, jfloat);

#ifdef __cplusplus
}
#endif
#endif
